spring:
  application:
    name: backend

  security:
    oauth2:
      resourceserver:
        jwt:
          jwt-set-uri: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_Tfd0F5MLe/.well-known/jwks.json
          issuer-uri: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_Tfd0F5MLe
          clientId: 73tq8kr3f2vnr6lvisgg36bkhj
          clientSecret: jpqqosgm5r7tr2lpasepgl8hmvd90g1ntt6f7ml1eqfgfa74ijv
          redirect-uri: http://localhost:5173/oauth2/idpresponse
auth.cognitoUri: https://ap-south-1tfd0f5mle.auth.ap-south-1.amazoncognito.com
